name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.15.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Configure git to use PAT
        run: |
          git config user.name "release-bot"
          git config user.email "release-bot@users.noreply.github.com"
          git remote set-url origin "https://SugarmanZhu:${RELEASE_TOKEN}@github.com/${{ github.repository }}.git"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Run semantic-release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
